# Makefile.common

######################################
# building variables
######################################
DEBUG = 0

ifeq ($(DEBUG), 1)
	OPT =
else
	OPTLVL = -O3
	OPT = $(OPTLVL) -fomit-frame-pointer -funroll-loops
endif

BUILD_DIR = build

#########################################
# LIBRARIES NEEDED FOR THIS APPLICATION #
#########################################

C_SOURCES += \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_gpio.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_usart.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_dma.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_rcc.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_utils.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_exti.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc_ex.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash_ex.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_gpio.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma_ex.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr_ex.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_cortex.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal.c \
	Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_exti.c \

C_INCLUDES += \
	-IDrivers/STM32H5xx_HAL_Driver/Inc \
	-IDrivers/CMSIS/Device/ST/STM32H5xx/Include \
	-IDrivers/CMSIS/Include \

#### EOF
